name: ì•ˆë…•, ê¹ƒí—ˆë¸Œ ì•¡ì…˜ - input ë°›ê¸°

on:
  pull_request:
    types: opened
        
jobs:
  Hello-GitHub-Action:
    runs-on: ubuntu-latest
    name: ì•ˆë…• ì¸ì‚¬ ğŸ™ŒğŸ»

    steps:
      - name: ì•ˆë…•í•˜ì„¸ìš”, ê¹ƒí—™ ì•¡ì…˜
        run: |
            echo "ë”°ëœ»í•œ í™˜ì˜ ê³ ë§ˆì›Œìš”! ì €ì˜ ì´ë¦„ì€ hyelim ì…ë‹ˆë‹¤"
