name: ì•ˆë…•, ê¹ƒí—ˆë¸Œ ì•¡ì…˜ - input ë°›ê¸°

on: 
  workflow_dispatch:
    inputs:
      myName:
        description: "ì´ë¦„ì„ ì…ë ¥í•´ì£¼ì„¸ìš”"
        required: true
        default: ''
        
jobs:
  Hello-GitHub-Action:
    runs-on: ubuntu-latest
    name: ì•ˆë…• ì¸ì‚¬ ğŸ™ŒğŸ»

    steps:
      - name: ì•ˆë…•í•˜ì„¸ìš”, ê¹ƒí—ˆë¸Œ ì•¡ì…˜
        run: |
            echo "ë”°ëœ»í•œ í™˜ì˜ ê³ ë§ˆì›Œìš”! ì €ì˜ ì´ë¦„ì€ ${{ github.event.inputs.myName}} ì…ë‹ˆë‹¤"
